DESTDIR= 
CC=gcc 
CFLAGS= 

all:

install: 
	cp    email2text.sh $(DESTDIR)/usr/bin/mail2text
	cp    mail-bot.pl $(DESTDIR)/usr/sbin/mail-bot
	cp    smtp2xmpp.pl $(DESTDIR)/usr/bin/smtp2xmpp
	cp    xmpp2smtp.sh $(DESTDIR)/usr/sbin/xmpp2smtp
	cp    xmpp_smtp $(DESTDIR)/etc/init.d/

clean: 
